channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake=7.16.0
  - python=3.9
  - pip
  - pandas=1.3.2
  - cutadapt=3.5
  - bwa=0.7.17
  - samtools>=1.8
  - gatk4=4.1.9.0
  - perl-bioperl
  - svaba
  - bedtools>=2.22
  - r-base>=4.0
  - r-ggplot2
  - r-hexbin
  - r-optparse
  - r-caret
  - r-gbm
  - r-glmnet
  - r-randomforest
  - r-smotefamily
  - r-perfmeas
  - r-yardstick
  - r-dplyr
  - r-gridextra
  - bioconductor-deseq2>=1.20
  - py-bgzip
  - tabix
  - vcftools
  - cas-offinder
  - ir
  - pip:
    - azimuth